- block:
    - name: Install EPEL
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present

    - name: Install Base Packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - python-pip
        - python-devel
        - sshpass
        - gcc
        - libffi-devel
        - openssl-devel
        - vim

    - name: Install Ansible via PIP
      pip:
        name: ansible
        state: present

    - name: Upgrade setuptools via PIP
      pip:
        name: setuptools
        state: latest
  when: install_ansible

- name: Install packages on control
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - git

- name: Create ssh dir
  file:
    state: directory
    path: /home/{{ username }}/.ssh
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: o-rwx

- name: Set Deployment Key
  copy:
    src: "{{ role_path }}/files/deploy_key"
    dest: /home/{{ username }}/.ssh/id_rsa
    mode: 0400
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Clone lightbulb
  git:
    accept_hostkey: yes
    clone: yes
    dest: /home/{{ username }}/lightbulb
    key_file: /home/{{ username }}/.ssh/id_rsa
    repo: git@github.com:ansible/lightbulb.git
    force: yes

- name: Remove deployment key
  file:
    state: absent
    path: /home/{{ username }}/.ssh/id_rsa

- name: Update Perms for Git Clone
  file:
    state: directory
    recurse: yes
    owner: "{{ username }}"
    group: "{{ username }}"
    path: /home/{{ username }}/lightbulb

- name: Remove things that students don't need
  file:
    state: absent
    path: /home/{{ username }}/lightbulb/{{ item }}
  with_items:
    - aws_lab_setup
    - resources
    - Vagrantfile
    - README.md

- name: Install AWS ansible.cfg in home directory
  copy:
    src: ansible.cfg
    dest: /home/{{ username }}/.ansible.cfg
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Create lab inventory directory
  file:
    state: directory
    path: /home/{{ username }}/lightbulb/lessons/lab_inventory

- name: Setup student inventory in proper spot
  copy:
    src: ./{{ username }}-instances.txt
    dest: /home/{{ username }}/lightbulb/lessons/lab_inventory/hosts
  when: "username in inventory_hostname"

- name: Update Perms from home dir down
  file:
    state: directory
    recurse: yes
    owner: "{{ username }}"
    group: "{{ username }}"
    path: /home/{{ username }}
