---
- hosts: web
  name: This is a Playbook
  sudo: yes

  vars:
    packages:
    - httpd
    - libselinux-python

  tasks:
  - name: stop iptables
    service: name=iptables state=stopped

  - name: install packages
    yum: name={{ item }} state=present
    with_items: packages

  - name: copy index.html
    copy: src=files/index.html dest=/var/www/html/
    notify: something happened

  - name: start and enable apache service
    service: name=httpd state=started enabled=yes

  handlers:
  - name: something happened
    shell: echo "file copied" >> /tmp/some.log