- name: install packages (Debian)
  apt: 
    name: "{{ item }}"
    state: present 
    update_cache: yes 
    cache_valid_time: 3600
  with_items: "{{ packages }}"
  tags: package

- name: enable CGI
  apache2_module:
    name: cgi
    state: present
